export const AllListings = [
  {'mangaId': '-000000---ultra-black', 'name': '#000000 - Ultra Black'},
  {'mangaId': '-a-no-tachiichi', 'name': '+a no Tachiichi'},
  {'mangaId': '-anima', 'name': '+Anima'},
  {'mangaId': '-c-sword-and-cornett', 'name': '+C Sword and Cornett'},
  {'mangaId': '-junjou-drop', 'name': ' Junjou Drop'},
  {'mangaId': '-kanchigai-hime-to-usotsuki-shimobe', 'name': ' Kanchigai Hime to Usotsuki Shimobe'},
  {'mangaId': '-musashi-kun-to-murayama-san-wa-tsukiatte-mita-', 'name': ' Musashi-kun to Murayama-san wa Tsukiatte Mita.'},
  {'mangaId': '-tobaku-datenroku-kaiji--kazuyahen', 'name': ' Tobaku Datenroku Kaiji: Kazuyahen'},
  {'mangaId': '-welcome-to-ghost-city', 'name': ' Welcome to Ghost City'},
  {'mangaId': '0-0-mhz', 'name': '0.0 Mhz'},
  {'mangaId': '0-noushiya-minato', 'name': '0-noushiya Minato'},
  {'mangaId': '009-re-cyborg', 'name': '009 Re:Cyborg'},
  {'mangaId': '07-ghost', 'name': '07 Ghost'},
  {'mangaId': '090---eko-to-issho', 'name': '090 - Eko To Issho'},
  {'mangaId': '1-11', 'name': '1/11'},
  {'mangaId': '1-2-love-', 'name': '1/2 Love!'},
  {'mangaId': '1-2-prince', 'name': '1/2 Prince'},
  {'mangaId': '1-3-no-kareshi', 'name': '1/3 No Kareshi'},
  {'mangaId': '1-3-romantica', 'name': '1/3 Romantica'},
  {'mangaId': '10-dance', 'name': '10 Dance'},
  {'mangaId': '1001', 'name': '1001'},
  {'mangaId': '11-eyes', 'name': '11 Eyes'}
];
