export const RecommendedListing = [
  {'title': '20th Century Boys', 'mangaId': '20th-century-boys'},
  {'title': 'Akira', 'mangaId': 'akira'},
  {'title': 'Shingeki no Kyojin', 'mangaId': 'shingeki-no-kyojin'},
  {'title': 'Battle Angel Alita Last Order', 'mangaId': 'battle-angel-alita-last-order'},
  {'title': 'Beelzebub', 'mangaId': 'beelzebub'},
  {'title': 'Bleach', 'mangaId': 'bleach'},
  {'title': 'Claymore', 'mangaId': 'claymore'},
  {'title': 'Deadman Wonderland', 'mangaId': 'deadman-wonderland'},
  {'title': 'Fairy Tail', 'mangaId': 'fairy-tail'},
  {'title': 'Gantz', 'mangaId': 'gantz'},
  {'title': 'Naruto', 'mangaId': 'naruto'},
  {'title': 'One Piece', 'mangaId': 'one-piece'},
  {'title': 'Soul Eater', 'mangaId': 'soul-eater'},
  {'title': 'Vagabond', 'mangaId': 'vagabond'},
  {'title': 'Onepunch-Man', 'mangaId': 'onepunch-man'},
  {'title': 'Hellsing', 'mangaId': 'hellsing'},
  {'title': 'Fist of the North Star', 'mangaId': 'fist-of-the-north-star'},
  {'title': 'Black Lagoon', 'mangaId': 'black-lagoon'},
  {'title': 'Dragon Ball', 'mangaId': 'dragon-ball'},
  {'title': 'Neon Genesis Evangelion', 'mangaId': 'neon-genesis-evangelion'},
  {'title': 'xxxHolic', 'mangaId': 'xxxholic'},
  {'title': 'Blade of the Immortal', 'mangaId': 'blade-of-the-immortal'},
  {'title': 'Full Metal Alchemist', 'mangaId': 'full-metal-alchemist'},
  {'title': 'Black Cat', 'mangaId': 'black-cat'},
  {'title': 'Guyver', 'mangaId': 'guyver'},
  {'title': 'Great Teacher Onizuka', 'mangaId': 'great-teacher-onizuka'},
  {'title': 'School Rumble', 'mangaId': 'school-rumble'},
  {'title': 'Detroit Metal City', 'mangaId': 'detroit-metal-city'}
];
